### ISSUE TITLE
The output image is of dimension : 792*81

### ISSUE THREAD

**Issue by abhinav3** [TuBui/color-GFHoG#1]
Hi, 
So I tried running the example.m file with command `des = ComputeGF('circle.png',0);`
But the output `des` is of dimension 792*81 and not like the one shown in readme.
Am I missing something here?

**Comment by TuBui** [comment]
This computes the local descriptors only (you have 792 local descriptors each of dimension 81-D). `GF-HoG` is just like `HoG` and `SIFT` as they are local descriptors. To get global descriptor you need to go through the standard Bag of Words method which requires a whole image set, as described in the paper.

**Comment by abhinav3** [comment]
Hi,
Could you pls share the code part so that I could obtain the "GF-HoG" final image.

**Comment by TuBui** [comment]
When you say "final image" do you mean the gradient field visualisation as shown in README?
It should be generated by default as a file named `circle_gf.png`. Did you check your folder where you run the code?

**Comment by abhinav3** [comment]
Oh cool, Thanks a lot !
